update multiple configs
- .bashrc
- fish config
- hyprland

diff --git a/scripts/zk-new b/scripts/zk-new
--- a/scripts/zk-new
+++ b/scripts/zk-new
@@ -1,3 +1,13 @@
 #!/usr/bin/env bash
 
+if [ $# -eq 0 ]; then
+    echo "Usage: zk-new <title>"
+    exit 1
+fi
+
+if not command -v zk >/dev/null 2>&1; then
+    echo "Error: 'zk' command not found."
+    exit 1
+fi
+
 zk new --title "$@"
